project:
  type: website


email: info@oegd-bb.de

website:
  title: "ÖGD Brandenburg Berlin"
  description: "Wir sind der Verband der Ärztinnen und Ärzte des Öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V.! Wir setzen uns ein für die Gesundheit der Bürgerinnen und Bürger, die Interessen der Mitglieder und denen der Beschätigten im Öffentlichen Gesundheitsdienst."
  site-url: https://oegd-bb.de
  search: true
  favicon: img/favicon.ico
  back-to-top-navigation: true
  image: logo_klein.png
  open-graph: true
  navbar:
    logo: img/logo_klein.png
    left:
      - href: index.qmd
        text: Startseite
      - href: pages/mitgliedschaft.qmd
        text: Mitgliedschaft
      - href: pages/neuigkeiten.qmd
        text: Neuigkeiten
      - href: pages/oegd.qmd
        text: ÖGD
      - href: pages/about.qmd
        text: Über
  page-footer: 
    left: "ÖGD Brandenburg Berlin" 
    right: 
      - href: pages/impressum.qmd#datenschutzerklärung
        text: Datenschutz
      - href: pages/impressum.qmd
        text: Impressum 
      - href: pages/impressum.qmd#copyright
        text: Copyright
      - href: pages/impressum.qmd#haftungshinweise
        text: Haftungshinweise
      - href: pages/impressum.qmd#bildquellen
        text: Bildquellen 
      - text: Fehlermeldung
        href: https://github.com/


format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true


execute:
  freeze: auto


