---
title: "Impressum"
lang: de
---

Herausgeber der Internetseite ist Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V.

Inhaltlich verantwortlich gemäß Paragraf 55 Rundfunkstaatsvertrag (RfStV) und § 5 Telemediengesetz (TMG) ist der Vorstand des Verbandes der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V.

### Vorsitz
Katharina Sandau 

### Redaktion  
Dr. Jakob Schumacher

## Haftungshinweise
Der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. prüft und aktualisiert die Informationen auf seiner Webseite ständig. Trotz aller Sorgfalt können sich die Daten verändert haben. Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen kann nicht übernommen werden. Gleiches gilt auch für alle anderen Websites, auf die mittels Hyperlink verwiesen wird. Der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. ist für den Inhalt der Website, die aufgrund einer solchen Verbindung erreicht wird, nicht verantwortlich.

Des Weiteren behält sich der Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. das Recht vor, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.

Inhalt und Struktur der Websites des Verband der Ärztinnen und Ärzte des öffentlichen Gesundheitsdienstes der Länder Brandenburg und Berlin e.V. sind urheberrechtlich geschützt.

## Danksagung
* [Posit.co](https://posit.co/) für die Software RStudio
* [Quarto.org](https://quarto.org/) für die Software quarto
* [Github.com](https://github.com/) für die Arbeitsumgebung
* [Iconify](https://iconify.design/) für die Grafiken

## Bildquellen 
* Foto von <a href="https://unsplash.com/de/@markusspiske?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Markus Spiske</a> auf <a href="https://unsplash.com/de/fotos/P0klwkGbH_M?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@jonasjacobsson?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jonas Jacobsson</a> auf <a href="https://unsplash.com/de/fotos/2xaF4TbjXT0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@golfarisa?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Arisa Chattasa</a> auf <a href="https://unsplash.com/de/fotos/0LaBRkmH4fM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@gabriellefaithhenderson?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Gabrielle Henderson</a> auf <a href="https://unsplash.com/de/fotos/HJckKnwCXxQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@neonbrand?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Kenny Eliason</a> auf <a href="https://unsplash.com/de/fotos/1-aA2Fadydc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@nate_dumlao?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Nathan Dumlao</a> auf <a href="https://unsplash.com/de/fotos/ewGMqs2tmJI?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
* Foto von <a href="https://unsplash.com/de/@cwmonty?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Chris Montgomery</a> auf <a href="https://unsplash.com/de/fotos/smgTvepind4?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
*  [Rathaus Spandau: A.Savin - Eigenes Werk - Mediawiki](https://de.wikipedia.org/wiki/Rathaus_Spandau#/media/Datei:Rathaus_B-Spandau_07-2017.jpg)   
* [Potsdam: Kai Vogel - Mediawiki](https://pixabay.com/en/potsdam-babelsberg-downtown-green-1859455/) [Archivkopie](https://de.wikipedia.org/wiki/Potsdam#/media/Datei:Havel-Park-Lake-Babelsberg-Downtown-Potsdam-Green.jpg)
  
  

## Copyright
Sofern zur Verwendung von im Internetangebot veröffentlichten Inhalten spezielle Nutzungsbedingungen festgelegt sind, gelten diese vorrangig. Ein Download oder Ausdruck von Inhalten ausschließlich für den persönlichen Gebrauch sind gestattet. Alle Inhalte, Bilder oder Grafiken sind urheberrechtlich geschützt und dürfen nur mit schriftlicher Genehmigung des jeweiligen Rechteinhabers verwendet werden.  
  
## Datenschutzerklärung

Für den Verband der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V. hat ein verantwortungsbewusster Umgang mit personenbezogenen Daten hohe Priorität. Wir möchten, dass Nutzerinnen und Nutzer dieser Webseite wissen, wann welche Daten durch den Verband erhoben und verwendet werden.

Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.


### Personenbezogene Daten

Die Nutzung des Webangebots des Verbandes der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V. ist grundsätzlich ohne Bekanntgabe personenbezogener Informationen möglich.
Datenerfassung und -speicherung

Wenn Sie uns eine Nachricht mittels E-Mail senden, so werden Ihre Daten für die Korrespondenz mit Ihnen verwendet.

Sollten wir eine Nachricht über eine E-Mail von Ihnen erhalten, gehen wir davon aus, dass wir zu einer Beantwortung per E-Mail berechtigt sind. Ansonsten müssen Sie uns ausdrücklich auf eine andere Art der Kommunikation hinweisen.

Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.

Bei der Beantragung von Mitgliedschaft im Verband, wird nach Namen und anderen persönlichen Informationen gefragt. Es unterliegt dabei der freien Entscheidung der Nutzerinnen und Nutzer, ob sie diese Daten mitteilen möchten. Entsprechende Angaben werden dabei vom Vorstand des Vereins im Rahmen der gesetzlichen Fristen aufbewahrt. Der Zugriff darauf ist nur wenigen befugten Personen möglich.


### Weitergabe personenbezogener Daten an Dritte
Soweit im Rahmen der Vereinsaufgaben personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.

Daten, die beim Zugriff auf das Internetangebot des Verbandes der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V erfasst worden sind, werden nur an Dritte übermittelt, wenn der Verbandes der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V zu einer Übermittlung gesetzlich oder durch Gerichtsentscheidung verpflichtet ist oder die Weitergabe im Falle von Angriffen auf die Internetinfrastruktur des Verbandes der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V zur Rechts- oder Strafverfolgung erforderlich ist.

Eine Weitergabe zu anderen nicht-kommerziellen oder zu kommerziellen Zwecken erfolgt nicht.


### Einsatz von Cookies
Die Internetseiten verwenden teilweise so genannte Cookies. Cookies richten auf Ihrem Rechner keinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert.

Die meisten Browser sind so eingestellt, dass sie Cookies automatisch akzeptieren. Das Speichern von Cookies kann jedoch deaktiviert oder der Browser so eingestellt werden, dass Cookies nur für die Dauer der jeweiligen Verbindung zum Internet gespeichert werden.

Die meisten der von uns verwendeten Cookies sind so genannte „Session-Cookies“. Sie werden nach Ende Ihres Besuchs automatisch gelöscht. Andere Cookies bleiben auf Ihrem Endgerät gespeichert, bis Sie diese löschen. Diese Cookies ermöglichen es uns, Ihren Browser beim nächsten Besuch wiederzuerkennen.

### Minderjährigenschutz
Personen unter 18 Jahren sollten ohne Zustimmung der Eltern oder Erziehungsberechtigten keine personenbezogenen Daten an uns übermitteln. Wir fordern keine personenbezogenen Daten von Kindern und Jugendlichen an. Wissentlich sammeln wir solche Daten nicht und geben sie auch nicht an Dritte weiter.
Datenschutzerklärung für die sozialen Medien

Der Verband der Ärzte des Öffentlichen Gesundheitsdienstes der Länder Berlin und Brandenburg e.V nimmt die derzeitige Diskussion um den Datenschutz in sozialenNetzwerken sehr ernst. Es ist gegenwärtig rechtlich nicht abschließend geklärt, ob und inwieweit alle Netzwerke ihre Dienste im Einklang mit europäischen datenschutzrechtlichen Bestimmungen anbieten.

### Server-Log-Files
Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log Files, die Ihr Browser automatisch an uns übermittelt. Dies sind:

* Browsertyp und Browserversion
* verwendetes Betriebssystem
* Referrer URL
* Hostname des zugreifenden Rechners
* Uhrzeit der Serveranfrage

Diese Daten sind nicht bestimmten Personen zuordenbar. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Wir behalten uns vor, diese Daten nachträglich zu prüfen, wenn uns konkrete Anhaltspunkte für eine rechtswidrige Nutzung bekannt werden.

### Recht auf Auskunft, Löschung, Sperrung
Sie haben jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung sowie ein Recht auf Berichtigung, Sperrung oder Löschung dieser Daten.

Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden.
Änderungen der Datenschutzerklärung

Im Zuge der (technologischen) Weiterentwicklung unserer Webseite können Änderungen dieser Datenschutzerklärung erforderlich werden. Daher wird empfohlen, sich diese Datenschutzerklärung ab und zu erneut durchzulesen.

### SSL-Verschlüsselung
Diese Seite nutzt aus Gründen der Sicherheit und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel der Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von "http://" auf "https://" wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.

Wenn die SSL Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.

