---
title: "Mitgliedschaft im Verein"
lang: de
---


## Seien Sie Dabei: Mitglied werden!

:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-1-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Möglichkeit prüfen
Alle Ärztinnen und Ärzte, Zahnärztinnen und Zahnärzte sowie Fachkräfte im Öffentlichen Gesundheitsdienst der Länder Brandenburg oder Berlin können Mitglied werden.
::: 
::::




:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-2-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Vorteile der Mitgliedschaft
* Sie können an der Gestaltung des öffentlichen Gesundheitsdienstes aktiv mitwirken.
* Sie können Ihre beruflichen Interessen wirksam vertreten lassen.
* Sie sind über die Entwicklungen im öffentlichen Gesundheitsdienst gut informiert.
* Sie genießen Sie Unterstützung in beruflichen Rechtsfragen.
* Sie profitieren von den Vorteilen, die der Bundesverband {{< iconify eva external-link-fill size=1x >}} [BVÖGD.de](https://bvoegd.de) bietet.
* Sie können Sich fortbilden lassen 
* Sie können sich über die Facharztweiterbildung zum Facharzt ÖGW informieren
* Sie können zu vergünstigten Konditionen am wissenschaftlichen {{< iconify eva external-link-fill size=1x >}} [Kongress des BVÖGD und BZÖG](https://bvoegd-kongress.de/) teilnehmen.

::: 

::::


:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-3-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Wichtige Dokumente kennen lernen
Lernen Sie die {{< iconify solar document-add-linear size=1x >}}&nbsp;[Satzung](../documents/satzung.pdf) und die {{< iconify solar document-add-linear size=1x >}}&nbsp;[Beitragsordnung](../documents/Beitragsordnung.pdf) kennen 
::: 
::::




:::: {.columns}

::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-4-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Aufnahmeantrag ausfüllen und abschicken
{{< iconify solar document-add-linear size=1x >}}&nbsp;[Mitgliedsantrag](../documents/Antrag_auf_Mitgliedschaft_Einzugsermaechtigung_2019-02-23.pdf) und die {{< iconify solar document-add-linear size=1x >}}&nbsp;[Einzugsermächtigung](../documents/Einzugsermaechtigung.pdf) für die Mitgliedschaft herunterladen und ausfüllen.


Bitte senden Sie das ausgedruckte und ausgefüllte Original (Aufnahmeantrag & Einzugsermächtigung) an den oder die Schatzmeister*in.
::: 

::::

## Es gibt eine Änderung: Schicken Sie uns ein Update!

:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-1-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Änderungen einer Adresse
Der Verein führt eine Mitgliedsliste. Wichtig ist vor allem die private E-Mail-Adresse, denn hierüber werden die wichtigen Informationen versendet. Wenn sich hier etwas geändert hat schicken Sie uns bitte einen {{< iconify solar document-add-linear size=1x >}}&nbsp;[Änderungsantrag](../documents/Aktualisierung.pdf) 
::: 
::::

:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-2-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Änderungen der Bankverbindung
Sie haben die Bank gewechselt? Schicken Sie uns bitte eine neue {{< iconify solar document-add-linear size=1x >}}&nbsp;[Einzugsermächtigung](../documents/Einzugsermaechtigung.pdf) 
::: 
::::


## Sie wollen austreten: Senden Sie eine Kündigung!

:::: {.columns}
::: {.column width="20%"}
::: {style="color:#b9031c;text-align:center;margin-top:20%"}
{{< iconify fluent number-circle-1-32-regular size=4x >}}
::: 
::: 
::: {.column width="75%"}
### Austritt
Sie wollen uns verlassen? Das bedauern wir sehr. Schicken Sie uns eine formlose E-Mail an [info@oegd-brandenburg-berlin.de](mailto:info@oegd-brandenburg-berlin.de). Gibt es besondere Gründe warum Sie austreten? Melden Sie sich bei gerne bei einem Vorstandmitglied. 
::: 
::::
